# Generated by Django 4.1.7 on 2023-04-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_printers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='printer_type',
            field=models.CharField(choices=[('inkjet', 'Inkjet'), ('laser', 'Laser')], default='inkjet', max_length=24),
        ),
    ]
